#!/usr/bin/env python3

"""
Connect to MDB_URI and add a random amount to a random user's score every 2 seconds.

This script is designed to test the leaderboard interface updating as the underlying data source is updated.
"""

import os
import random
import time

from pymongo import MongoClient


class Updater:
    def __init__(self, uri):
        self.mdb = MongoClient(uri)

    def update_one(self):
        scores = self.mdb.get_default_database().scores
        doc = next(
            scores.aggregate(
                [
                    {"$sample": {"size": 1}},
                ]
            )
        )
        inc = random.randint(10, 100)
        scores.update_one({"_id": doc["_id"]}, {"$inc": {"score": inc}})
        print(f"Updated: {doc['username']} by {inc}")


def main():
    updater = Updater(os.environ["MDB_URI"])
    try:
        while True:
            updater.update_one()
            time.sleep(2)
    except KeyboardInterrupt:
        pass


if __name__ == "__main__":
    main()