push:
    realm-cli push \
        --include-hosting \
        --reset-cdn-cache \
        --yes

deploy:
    cd app && npm run build
    just push

connect:
    mongosh $MDB_URI

init:
    mongosh $MDB_URI scripts/init_scores.js

rolling:
    ./scripts/rolling_updates

roll_players:
    ./scripts/rolling_player_updates

sync:
    mongosh $MDB_URI scripts/synchronize.js